### ISSUE TITLE
ModuleNotFoundError: No module named 'altair.vegalite.v4'

### ISSUE THREAD

**Issue by achaosss** [Malikk1997/Chat-Pdf#1]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\大模型\Chat-Pdf\chat_pdf_code.py", line 7, in <module>
    import streamlit as st
  File "C:\Users\Administrator\Desktop\大模型\Chat-Pdf\venv\lib\site-packages\streamlit\__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "C:\Users\Administrator\Desktop\大模型\Chat-Pdf\venv\lib\site-packages\streamlit\delta_generator.py", line 43, in <module>
    from streamlit.elements.arrow_altair import ArrowAltairMixin
  File "C:\Users\Administrator\Desktop\大模型\Chat-Pdf\venv\lib\site-packages\streamlit\elements\arrow_altair.py", line 36, in <module>
    from altair.vegalite.v4.api import Chart
ModuleNotFoundError: No module named 'altair.vegalite.v4'

**Comment by Malikk1997** [comment]
You need to install specific versions
pip install altair==4.1.0
pip install streamlit==0.87.0
